services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - meilisearch
            - redis
            - mysql 

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - sail


    mysql:
       image: 'mysql:8.0'
       ports:
         - '3306:3306'
       environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: delivery_laravel
       volumes:
         - 'sail-mysql:/var/lib/mysql'
       networks:
         - sail        
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s

    redis:
        image: redis:alpine
        ports:
           - '${REDIS_PORT:-6379}:6379'
        networks:
           - sail
        volumes:
            - 'sail-redis:/data'


networks:
    sail:
        driver: bridge
volumes:
    sail-meilisearch:
        driver: local
    sail-redis:
        driver: local
    sail-mysql:
        driver: local    
